stages:
 - build

cache:
  key: "$CI_BUILD_REF_NAME node:10"
  paths:
    - node_modules/

#
# BUILD
# Downloads dependencies and then runs Webpack build.
#
build:
  stage: build
  image: node:10
  before_script:
    - npm install
  script:
    - npm run build
  artifacts: 
    paths: 
      - dist/