pull_request_rules:
  - name: automatic merge
    conditions:
      - author=TimGeerts
      - status-success=Travis CI - Pull Request
    actions:
      delete_head_branch: {}
      merge:
        method: squash
        strict: true
