pull_request_rules:
  - name: delete HEAD after merge
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: automatic merge when CI passes and 1 review
    conditions:
      - status-success=continuous-integration/travis-ci/pr
      - '#approved-reviews-by>=1'
    actions:
      merge:
        method: merge
